export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const SET_ARTICLES = 'SET_ARTICLES';
export const SET_COORDINATES = 'SET_COORDINATES';
export const SET_ARTICLE_COORDINATES = 'SET_ARTICLE_COORDINATES'